module.exports = {
  Tag: require('./Base/Tag'),
  Icon: require('./Base/Icon'),
  Form: require('./Base/Form'),
  Card: require('./Base/Card'),
  Label: require('./Base/Label'),
  Tab: require('./Base/Tabs').Tab,
  Select: require('./Base/Select'),
  Tabs: require('./Base/Tabs').Tabs,
  Menu: require('./Menu/Menu').Menu,
  Button: require('./Button/Button'),
  Message: require('./Base/Message'),
  Checkbox: require('./Base/Checkbox'),
  Input: require('./Base/Input').Input,
  Panel: require('./Panel/Panel').Panel,
  MenuList: require('./Menu/Menu').MenuList,
  MenuItem: require('./Menu/Menu').MenuItem,
  HelpText: require('./Base/Input').HelpText,
  MenuLabel: require('./Menu/Menu').MenuLabel,
  Notification: require('./Base/Notification'),
  PanelTabs: require('./Panel/Panel').PanelTabs,
  LoadingSpinner: require('./Base/LoadingSpinner'),
};